routers:
  hosts:
    10.99.254.23:
      igp_int: gigabitethernet2
      igp_net: 10.10.10.0
      igp_ip: 10.10.10.1
      igp_mask: 255.255.255.252
      igp_inst_id: 10
      mgmt_loop_num: 255
      mgmt_loop: 10.1.1.1
      mgmt_mask: 255.255.255.255
    10.99.254.25:
      igp_int: gigabitethernet2
      igp_net: 10.10.10.0
      igp_ip: 10.10.10.2
      igp_inst_id: 10
      igp_mask: 255.255.255.252
      mgmt_loop_num: 255
      mgmt_loop: 10.2.2.2
      mgmt_mask: 255.255.255.255
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: cisco
    ansible_password: cisco123
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco123
    ansible_connection: ansible.netcommon.network_cli

switches:
  hosts:
    10.99.254.30:
      mgmt_loop_num: 255
      mgmt_loop: 10.3.3.3
      mgmt_mask: 255.255.255.255
      access_vlan: 100
      voice_vlan: 200
      range_start: 2
      range_end: 3
  vars:
    radius_server_group: ise-radius-group
    radius_servers: 
      - name: ise01
        ip: 10.99.10.123
        secret: cisco123
        authPort: 1812
        acctPort: 1813
      - name: ise02
        ip: 10.99.10.124
        secret: cisco123
        authPort: 1812
        acctPort: 1813
    ansible_network_os: cisco.ios.ios
    ansible_user: cisco
    ansible_password: cisco123
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco123
    ansible_connection: ansible.netcommon.network_cli