switches:
  hosts:
    10.99.254.30:
      mgmt_loop_num: 255
      mgmt_loop: 10.3.3.3
      mgmt_mask: 255.255.255.255
      access_vlan: 100
      voice_vlan: 200
    10.99.254.31:
      mgmt_loop_num: 255
      mgmt_loop: 10.4.4.4
      mgmt_mask: 255.255.255.255
      access_vlan: 300
      voice_vlan: 400
  vars:
    radius_server_group: ise-radius-group
    radius_servers: 
      - name: ise01
        ip: 10.99.10.123
        secret: cisco123
        authPort: 1812
        acctPort: 1813
      - name: ise02
        ip: 10.99.10.124
        secret: cisco123
        authPort: 1812
        acctPort: 1813
    ansible_network_os: cisco.ios.ios
    ansible_user: cisco
    ansible_password: cisco123
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco123
    ansible_connection: ansible.netcommon.network_cli