---

- name: Cisco Router Management
  hosts: routers
  gather_facts: false

  tasks:
    - name: Configure Named Access Control List
      cisco.ios.ios_config:
        lines:
        - 10 permit udp any host 8.8.8.8 eq domain
        - 20 permit udp any host 4.2.2.2 eq domain
        parents: ip access-list extended AnsibleACL
        before: no ip access-list extended AnsibleACL
        match: exact

    - name: Configure Numbered Access Control List
      cisco.ios.ios_config:
        lines:
        - access-list 100 permit udp any host 8.8.8.8 eq domain
        - access-list 100 permit udp any host 4.2.2.2 eq domain
        before: no access-list 100
        match: exact

    - name: Configure IGP Connection
      cisco.ios.ios_config:
        lines:
        - ip address {{ igp_ip }} {{ igp_mask }}
        - no shut
        parents: '{{ item }}'
      with_items:
      - interface {{ igp_int }}

    - name: Configure Management Loopback
      cisco.ios.ios_config:
        lines:
        - description ** Management Loopback Interface **
        - ip address {{ mgmt_loop }} {{ mgmt_mask }}
        parents: interface loopback {{ mgmt_loop_num }}

    - name: Configure IGP
      cisco.ios.ios_config:
        lines:
        - network 10.10.10.0 0.0.0.255
        - passive-interface default
        - no passive-interface {{ igp_int }}
        - redistribute connected
        parents: router eigrp {{ igp_inst_id }}

    - name: Save Configuration
      cisco.ios.ios_config:
        save_when: modified