---

- name: Cisco Switch Management
  hosts: switches
  gather_facts: false

  tasks:
    - name: Configure Management Loopback
      cisco.ios.ios_config:
        lines:
        - description ** Management Loopback Interface **
        - ip address {{ mgmt_loop }} {{ mgmt_mask }}
        parents: interface loopback {{ mgmt_loop_num }}

    - name: Configure Access Ports
      cisco.ios.ios_config:
        lines:
        - switchport host
        - switchport access vlan {{ access_vlan }}
        - switchport voice vlan {{ voice_vlan }}
        parents: interface range gigabitethernet 0/{{ range_start }} - {{ range_end }}

    - name: Configure Access Ports
      cisco.ios.ios_config:
        lines:
        - switchport host
        - switchport access vlan {{ access_vlan }}
        - switchport voice vlan {{ voice_vlan }}
        parents: 
        - interface gigabitethernet 0/2
        - interface gigabitethernet 0/3

    - name: Save Configuration
      cisco.ios.ios_config:
        save_when: modified